CREATE DATABASE IF NOT EXISTS cpr_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cpr_user'@'localhost' IDENTIFIED BY '8iTBootQj4C0NRPt2CsIJExJ';
GRANT ALL PRIVILEGES ON cpr_db.* TO 'cpr_user'@'localhost';
FLUSH PRIVILEGES;
